#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  security:
#    enabled: false
#  metrics:
#    tags:
#      application: ${spring.application.name}
#  endpoint:
#    health:
#      show-details: ALWAYS